name: Deploy to Railway

on:
  workflow_dispatch:
    # Enable manual run
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:

  test:
    name: Run Tests
    uses: ./.github/workflows/test.yml

  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up
