name: Deploy to Railway

on:
  workflow_dispatch:
    # Enable manual run
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up
