name: Test

on:
  workflow_dispatch:
    # Enable manual run
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build-test:
    name: Run Tests
    uses: PipelinesWeb/app-frontend/.github/workflows/test.yml@main
